### ISSUE TITLE
Setup Readme, License, Code Of Conduct, and Contribution.md

### ISSUE THREAD

**Issue by thebongy** [thebongy/omen-cli#1]
- [ ] Need to setup a readme on the project with CLI Usage, and instructions to build the project from source
- [ ] Setup License
- [ ] Setup Code of Conduct
- [ ] Setup Contribution Guidelines

**Comment by ashikka** [comment]
@thebongy Can you assign this task to me?

**Comment by thebongy** [comment]
I have assigned the issue to you @ashikka , thank you so much for taking this up! ❤️

Here are some more details on what needs to be documented in the README.md:

## CLI Options
The README.md needs to document the `set4` and `set1` and --type options from the CLI. More info on the usage can be seen in the screenshot below
![image](https://user-images.githubusercontent.com/7080652/135879454-cb50f6eb-30f3-493e-aee9-93d18dea5e37.png)

`set4` is used to set 4 colors to the 4 zones on the keyboard
`set1` is used to set the same color to all 4 zones
`--type` can either be `rgb` or `name`, to give the colors in different formats

Additionally, it also needs to document steps to build the project:

## Prerequisites are:
- .NET Framework 4.5
- Nuget.exe CLI
- MSBuild.exe CLI


## Steps to Build:
- Clone the project
- Run `nuget install .\CLI\packages.config -OutputDirectory packages` to install dependencies
- Run `MSBuild.exe` from the root dir to build the project

**Comment by thebongy** [comment]
@ashikka the PR looks great! I have merged it
